### ISSUE TITLE
enable display of external links (VIKI)

### ISSUE THREAD

**Issue by krabina** [ProfessionalWiki/Network#19]
For documentation purposes, I am suggesting features that were present in the VIKI extension and could be improvments for the network extension in the future. 

A link to an URL outside the wiki is also shown in VIKI, but not in network extension. If a favicon is present, it was used:
![grafik](https://user-images.githubusercontent.com/4318745/106286637-269d2e00-6246-11eb-88f9-8ba999489096.png)

**Comment by JeroenDeDauw** [comment]
Weird, I thought showing external links was already implemented. https://github.com/ProfessionalWiki/Network/blob/master/resources/js/ApiPageConnectionRepo.js#L62

It definitely worked at some point

**Comment by krabina** [comment]
This is possilble, I don't recall. It does not work in 1.3.0 (3d92b07), I just checked:
![grafik](https://user-images.githubusercontent.com/4318745/106294215-2f463200-624f-11eb-8fb8-d62511e3907f.png)

**Comment by vmlemon** [comment]
Apologies for resurrecting a closed issue (and, for probably picking the wrong venue, for my question), but is there a way of toggling whether, or not external HTTP URIs are added, to the graph? (In my use case, of building a tree of inheritance, between various software/hardware products, these links add clutter to the graphs, that's useless, since the URI nodes only spawn dead-end nodes). 

Thanks, in advance.

**Comment by krabina** [comment]
I don't think it is possible to configure the inclusion of external links. Maybe you should create a new feature request.

**Comment by vmlemon** [comment]
> I don't think it is possible to configure the inclusion of external links. Maybe you should create a new feature request.

Fair enough. I ended up just using the previous version, since although I like the look of the new one, and the tooltips, it's going to be more hassle, than it's worth, trying to bend it into what I want it to be. Thanks for the quick reply, and the excellent project, otherwise, though. :)
